client:
    container_name: client
    build: client
    tty: true
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=docker
      - PORT=4200
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/dist:/usr/src/app/dist
      - ./client/tsconfig.json:/usr/src/app/tsconfig.json
      - ./client/package.json:/usr/src/app/package.json
      - ./client/package-lock.json:/usr/src/app/package-lock.json
